name: Build and Push Docker Image to ACR

on:
  workflow_call:
    inputs:
      acr_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: Dockerfile
      dockerfile_context:
        required: false
        type: string
        default: .
    secrets:
      azure_client_id:
        required: true
      azure_tenant_id:
        required: true
      azure_subscription_id:
        required: true
      npm_token:
        required: false
      api_key:
        required: false

    outputs:
      tag:
        description: "Short SHA tag used for the image"
        value: ${{ jobs.build-and-push.outputs.tag }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.azure_client_id }}
          tenant-id: ${{ secrets.azure_tenant_id }}
          subscription-id: ${{ secrets.azure_subscription_id }}

      - name: Set Git SHA tag
        id: set_tag
        run: echo "tag=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Docker ACR Login
        run: az acr login --name ${{ inputs.acr_name }}

      - name: Docker Build and Push
        env:
          ACR_NAME: ${{ inputs.acr_name }}
          IMAGE_NAME: ${{ inputs.image_name }}
          TAG: ${{ steps.set_tag.outputs.tag }}
          DOCKERFILE_PATH: ${{ inputs.dockerfile_path }}
          DOCKERFILE_CONTEXT: ${{ inputs.dockerfile_context }}
          NPM_TOKEN: ${{ secrets.npm_token }}
          API_KEY: ${{ secrets.api_key }}
        run: |
          BUILD_ARGS=""

          if [ -n "$NPM_TOKEN" ]; then
            BUILD_ARGS+=" --build-arg NPM_TOKEN=$NPM_TOKEN"
          fi

          if [ -n "$API_KEY" ]; then
            BUILD_ARGS+=" --build-arg API_KEY=$API_KEY"
          fi

          docker build \
            -f "$DOCKERFILE_PATH" \
            $BUILD_ARGS \
            -t "$ACR_NAME.azurecr.io/$IMAGE_NAME:$TAG" \
            -t "$ACR_NAME.azurecr.io/$IMAGE_NAME:latest" \
            "$DOCKERFILE_CONTEXT"

          docker push "$ACR_NAME.azurecr.io/$IMAGE_NAME:$TAG"
          docker push "$ACR_NAME.azurecr.io/$IMAGE_NAME:latest"

